home/urls.py
from django.urls import path
from . import views

app_name = "home_app"
urlpatterns = [
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('45', views.home, name='home'),
    path('', views.index, name='index'),
    path('monthly_report_form', views.monthly_report_form, name='monthly_report_form'),
    path('generate_monthly_report', views.generate_monthly_report, name='generate_monthly_report')
    ]

labmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls')),
    path('', include('project.urls')),
    path('', include('schedule.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
import random
import calendar
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate,login, logout
from django.http import HttpResponseRedirect, HttpResponse

from .utils import quotes
from django.contrib.auth.decorators import login_required
from project.models import Project, Task, ProjectOwners
from .decorators import unauthenticated_user, allowed_users, admin_only

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

from datetime import datetime
# Create your views here.

#just adding a note to hopefully push to server for a restart
@unauthenticated_user
def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home_app:index')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'home/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home_app:login')


@login_required(login_url='home_app:login')
def home(request):

    try:
        pm_first_name = request.user.first_name
        pm_last_name = request.user.last_name
        pm_name = pm_first_name + ' ' + pm_last_name
        pm_user = ProjectOwners.objects.get(project_owner_concat_name=pm_name)
        planning_project_count = Project.objects.filter(project_owner=pm_user, project_status='Planning' ).count()
        ready_project_count = Project.objects.filter(project_owner=pm_user, project_status='Ready').count()
        progress_project_count = Project.objects.filter(project_owner=pm_user, project_status='In-progress').count()
        hold_project_count = Project.objects.filter(project_owner=pm_user, project_status='On-hold').count()
        completed_project_count = Project.objects.filter(project_owner=pm_user, project_status='Completed').count()

        if request.user.username == "jenT":
            length = len(quotes)
            rand_quote = random.randint(0, length)
            quote = quotes[rand_quote - 1]
            context = {
                'planning_project_count': planning_project_count,
                'ready_project_count': ready_project_count,
                'progress_project_count': progress_project_count,
                'hold_project_count': hold_project_count,
                'completed_project_count': completed_project_count,
                'quote': quote,
            }
        else:
            context = {
                'planning_project_count': planning_project_count,
                'ready_project_count': ready_project_count,
                'progress_project_count': progress_project_count,
                'hold_project_count': hold_project_count,
                'completed_project_count': completed_project_count,

            }
        return render(request, 'home.html', context)
    except ProjectOwners.DoesNotExist as e:
        pm_first_name = request.user.first_name
        pm_last_name = request.user.last_name
        pm_name = pm_first_name + ' ' + pm_last_name
        print(pm_name)

        return render(request, 'home.html')



@login_required(login_url='home_app:login')
@admin_only
def index(request):
    length = len(quotes)
    rand_quote = random.randint(0,length)
    quote = quotes[rand_quote-1]
    planning_project_count = Project.objects.filter(project_status='Planning').count()
    ready_project_count = Project.objects.filter(project_status='Ready').count()
    active_project_count = Project.objects.filter(project_status='In-progress').count()
    hold_project_count = Project.objects.filter(project_status='On-hold').count()
    completed_project_count = Project.objects.filter(project_status='Completed').count()

    planning_task_count = Task.objects.filter(task_status='Planning').count()
    ready_task_count = Task.objects.filter(task_status='Ready').count()
    active_task_count = Task.objects.filter(task_status='In-progress').count()
    hold_task_count = Task.objects.filter(task_status='On-hold').count()
    completed_task_count = Task.objects.filter(task_status='Completed').count()
    context = {
        'quote': quote,
        'planning_project_count':planning_project_count,
        'ready_project_count': ready_project_count,
        'active_project_count': active_project_count,
        'hold_project_count': hold_project_count,
        'completed_project_count': completed_project_count,
        'planning_task_count': planning_task_count,
        'ready_task_count': ready_task_count,
        'active_task_count': active_task_count,
        'hold_task_count': hold_task_count,
        'completed_task_count': completed_task_count,


    }
    return render(request, 'home/home.html', context)


@login_required(login_url='home_app:login')
def monthly_report_form(request):
    return render(request, 'home/monthly_report_form.html')


@login_required(login_url='home_app:login')
def generate_monthly_report(request):
    month = request.GET.get('month')
    year = request.GET.get('year')
    month_name = calendar.month_name[int(month)]

    #find first day of month
    start_date= datetime.strptime(f"{year}-{month}-01","%Y-%m-%d").date()

    #find last day of month
    if month == '12':
        end_date = datetime.strptime(f"{int(year)+1}-01-01", "%Y-%m-%d").date()
    else:
        end_date = datetime.strptime(f"{year}-{int(month)+1}-01", "%Y-%m-%d").date()

    filename = f'monthly_report_{month}_{year}.pdf'
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'

    canv = canvas.Canvas(response, pagesize=A4)

    #draw logo to report
    img_path = "static/images/core-logo.png"
    img = ImageReader(img_path)
    img_width, img_height = img.getSize()
    canv.drawImage(img, 0, A4[1] - img_height, width=img_width, height=img_height)

    #get the number of tasks created etc in a selected month and year
    task_month_created = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date).count()
    task_month_completed = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date, task_status='Completed').count()
    task_month_planning = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date,
                                               task_status='Planning').count()
    task_month_progress = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date,
                                              task_status='In-progress').count()

    #Title Section
    canv.setFillColorRGB(255, 255, 255)
    canv.setStrokeColorRGB(0.5, 0.5, 0.5)
    margin = 20
    title_rect_height = 40
    title_rect_y = 715
    title_rect_width = A4[0] - 2 * margin
    title_text = f"Laboratory Monthly Report for {month_name} {year}"
    canv.rect(margin, title_rect_y, title_rect_width, title_rect_height, stroke=1, fill=1)
    canv.setFillColorRGB(0, 0, 0)
    canv.setFont('Helvetica-Bold', 20)
    canv.drawString(margin + 10, title_rect_y + 15, title_text)

    #Body Section
    canv.setFont("Helvetica", 12)  # set font size back to 12
    canv.drawString(50, 680, f"This report provides a summary analysis of the Core Laboratory")
    canv.drawString(50, 650, f"The total amount of tasks created for the month was: {task_month_created}")
    canv.drawString(50, 630, f"The number of tasks completed for the month was: {task_month_completed}")
    canv.drawString(50, 610, f"The number of tasks in Planning state is: {task_month_planning}")
    canv.drawString(50, 590, f"The number of tasks in In-Progess state is: {task_month_progress}")
    canv.drawString(50, 575, f"The number of Sample Prep tasks created is: ")
    canv.drawString(50, 560, f"The number of Sample Prep tasks completed is: ")
    canv.save()
    return response

templates/home/home.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "home/home.css" %}">
  {% endblock %}

{% block page_title %}

{% endblock %}

{% block content %}
<br>
<center><h1>Status Page</h1></center>

<br>
<br>
<center><h2>Project Info</h2></center>
<section id="project">
    <div class="home">
        <center>
        <h3> # Planning - Projects</h3>
        <p> {{ planning_project_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Ready - Projects</h3>
        <p> {{ ready_project_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Active - Projects</h3>
        <p> {{ active_project_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # On-Hold - Projects</h3>
        <p> {{ hold_project_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Completed - Projects</h3>
        <p> {{ completed_project_count }}</p>
        </center>
    </div>
</section>
<br>
<br>
<center><h2>Task Info</h2></center>
<section id="task">
    <div class="home">
        <center>
        <h3> # Planning</h3>
        <p> {{ planning_task_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Ready </h3>
        <p> {{ ready_task_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Active </h3>
        <p> {{ active_task_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Completed </h3>
        <p> {{ completed_task_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # On-hold </h3>
        <p> {{ hold_task_count }}</p>
        </center>
    </div>
</section>
<br>
<br>
<section id="quotes">
    <center><h3>Inspirational quotes</h3></center>
    <br>
        {{ quote }}

</section>
{% endblock %}

templates/home/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
                    <p id = 'messages' >{{ message }}</p>
                {% endfor %}


			</div>
		</div>
	</div>
</body>

</html>

templates/home/monthly_report_form.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "home/home.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>testing monthly report</h2>

<form action="{% url 'home_app:generate_monthly_report' %}" method="get">
    <label for="month">Month:</label>
    <select name="month" id="month">
        <option value="01">January</option>
        <option value="02">February</option>
        <option value="03">March</option>
        <option value="04">April</option>
        <option value="05">May</option>
        <option value="06">June</option>
        <option value="07">July</option>
        <option value="08">August</option>
        <option value="09">September</option>
        <option value="10">October</option>
        <option value="11">November</option>
        <option value="12">December</option>
    </select>
    <label for="year">Year:</label>
    <input type="number" name="year" id="year" min="2020" max="2030" value="2023">
    <button type="submit">Generate Report</button>
</form>



{% endblock %}