home/urls.py
from django.urls import path
from . import views

app_name = "home_app"
urlpatterns = [
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('45', views.home, name='home'),
    path('', views.index, name='index'),
    path('monthly_report_form', views.monthly_report_form, name='monthly_report_form'),
    path('generate_monthly_report', views.generate_monthly_report, name='generate_monthly_report')
    ]

labmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls')),
    path('', include('project.urls')),
    path('', include('schedule.urls')),
]

project/urls.py
from django.urls import path
from . import views
from django.apps import AppConfig

app_name = "project_app"

urlpatterns = [
    path('project_home_page', views.home, name='project_home_page'),
    path('project_owners', views.project_owners, name='project_owners'),
    path('test_list', views.test_list, name='test_list'),
    path('edit_test_list/<test_id>', views.edit_test_list, name='edit_test_list'),
    path('delet_test_list/<test_id>', views.delete_test_list, name='delete_test_list'),
    path('technician_list', views.technician_list, name='technician_list'),
    path('task_home_page', views.task_home_page, name="task_home_page"),
    path('add_task', views.add_task, name="add_task"),
    path('edit_project/<project_id>', views.edit_project, name="edit_project"),
    path('coord_edit_project/<project_id>', views.coord_edit_project, name="coord_edit_project"),
    path('delete_project/<project_id>', views.delete_project, name="delete_project"),
    path('pm_edit_task/<task_id>', views.pm_edit_task, name="pm_edit_task"),
    path('full_edit_task/<task_id>', views.full_edit_task, name="full_edit_task"),
    path('schedule_edit_task/<int:task_id>', views.schedule_edit_task, name="schedule_edit_task"),
    path('edit_project_owner/<project_owner_id>', views.edit_project_owner, name="edit_project_owner"),
    path('delete_project_owner/<project_owner_id>', views.delete_project_owner, name="delete_project_owner"),
    path('delete_technician/<technician_id>', views.delete_technician, name="delete_technician"),
    path('task_pdf/<task_id>', views.task_pdf, name='task_pdf'),
    path('edit_reason_list', views.viewTaskEdit, name='edit_reason_list'),
    path('delete_edit_reason/<edit_id>', views.delete_edit_reason, name='delete_edit_reason'),
    path('modify_edit_reason/<edit_id>', views.modify_edit_reason, name="modify_edit_reason"),
    path('task_edit_track', views.task_edit_track, name='task_edit_track'),
    path('test', views.test, name='test'),

    ]

schedule/urls.py
from django.urls import path
from . import views

app_name = "schedule_app"
urlpatterns = [
    path('schedule_home', views.schedule_home, name='schedule_home'),
    path('schedule_pm', views.schedule_pm, name='schedule_pm'),
    path('schedule_global', views.schedule_global, name='schedule_global'),


    ]

home/models.py
from django.db import models

# Create your models here.

home/views.py
import random
import calendar
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate,login, logout
from django.http import HttpResponseRedirect, HttpResponse

from .utils import quotes
from django.contrib.auth.decorators import login_required
from project.models import Project, Task, ProjectOwners
from .decorators import unauthenticated_user, allowed_users, admin_only

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

from datetime import datetime
# Create your views here.

#just adding a note to hopefully push to server for a restart
@unauthenticated_user
def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home_app:index')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'home/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home_app:login')


@login_required(login_url='home_app:login')
def home(request):

    try:
        pm_first_name = request.user.first_name
        pm_last_name = request.user.last_name
        pm_name = pm_first_name + ' ' + pm_last_name
        pm_user = ProjectOwners.objects.get(project_owner_concat_name=pm_name)
        planning_project_count = Project.objects.filter(project_owner=pm_user, project_status='Planning' ).count()
        ready_project_count = Project.objects.filter(project_owner=pm_user, project_status='Ready').count()
        progress_project_count = Project.objects.filter(project_owner=pm_user, project_status='In-progress').count()
        hold_project_count = Project.objects.filter(project_owner=pm_user, project_status='On-hold').count()
        completed_project_count = Project.objects.filter(project_owner=pm_user, project_status='Completed').count()

        if request.user.username == "jenT":
            length = len(quotes)
            rand_quote = random.randint(0, length)
            quote = quotes[rand_quote - 1]
            context = {
                'planning_project_count': planning_project_count,
                'ready_project_count': ready_project_count,
                'progress_project_count': progress_project_count,
                'hold_project_count': hold_project_count,
                'completed_project_count': completed_project_count,
                'quote': quote,
            }
        else:
            context = {
                'planning_project_count': planning_project_count,
                'ready_project_count': ready_project_count,
                'progress_project_count': progress_project_count,
                'hold_project_count': hold_project_count,
                'completed_project_count': completed_project_count,

            }
        return render(request, 'home.html', context)
    except ProjectOwners.DoesNotExist as e:
        pm_first_name = request.user.first_name
        pm_last_name = request.user.last_name
        pm_name = pm_first_name + ' ' + pm_last_name
        print(pm_name)

        return render(request, 'home.html')



@login_required(login_url='home_app:login')
@admin_only
def index(request):
    length = len(quotes)
    rand_quote = random.randint(0,length)
    quote = quotes[rand_quote-1]
    planning_project_count = Project.objects.filter(project_status='Planning').count()
    ready_project_count = Project.objects.filter(project_status='Ready').count()
    active_project_count = Project.objects.filter(project_status='In-progress').count()
    hold_project_count = Project.objects.filter(project_status='On-hold').count()
    completed_project_count = Project.objects.filter(project_status='Completed').count()

    planning_task_count = Task.objects.filter(task_status='Planning').count()
    ready_task_count = Task.objects.filter(task_status='Ready').count()
    active_task_count = Task.objects.filter(task_status='In-progress').count()
    hold_task_count = Task.objects.filter(task_status='On-hold').count()
    completed_task_count = Task.objects.filter(task_status='Completed').count()
    context = {
        'quote': quote,
        'planning_project_count':planning_project_count,
        'ready_project_count': ready_project_count,
        'active_project_count': active_project_count,
        'hold_project_count': hold_project_count,
        'completed_project_count': completed_project_count,
        'planning_task_count': planning_task_count,
        'ready_task_count': ready_task_count,
        'active_task_count': active_task_count,
        'hold_task_count': hold_task_count,
        'completed_task_count': completed_task_count,


    }
    return render(request, 'home/home.html', context)


@login_required(login_url='home_app:login')
def monthly_report_form(request):
    return render(request, 'home/monthly_report_form.html')


@login_required(login_url='home_app:login')
def generate_monthly_report(request):
    month = request.GET.get('month')
    year = request.GET.get('year')
    month_name = calendar.month_name[int(month)]

    #find first day of month
    start_date= datetime.strptime(f"{year}-{month}-01","%Y-%m-%d").date()

    #find last day of month
    if month == '12':
        end_date = datetime.strptime(f"{int(year)+1}-01-01", "%Y-%m-%d").date()
    else:
        end_date = datetime.strptime(f"{year}-{int(month)+1}-01", "%Y-%m-%d").date()

    filename = f'monthly_report_{month}_{year}.pdf'
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'

    canv = canvas.Canvas(response, pagesize=A4)

    #draw logo to report
    img_path = "static/images/core-logo.png"
    img = ImageReader(img_path)
    img_width, img_height = img.getSize()
    canv.drawImage(img, 0, A4[1] - img_height, width=img_width, height=img_height)

    #get the number of tasks created etc in a selected month and year
    task_month_created = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date).count()
    task_month_completed = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date, task_status='Completed').count()
    task_month_planning = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date,
                                               task_status='Planning').count()
    task_month_progress = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date,
                                              task_status='In-progress').count()

    #Title Section
    canv.setFillColorRGB(255, 255, 255)
    canv.setStrokeColorRGB(0.5, 0.5, 0.5)
    margin = 20
    title_rect_height = 40
    title_rect_y = 715
    title_rect_width = A4[0] - 2 * margin
    title_text = f"Laboratory Monthly Report for {month_name} {year}"
    canv.rect(margin, title_rect_y, title_rect_width, title_rect_height, stroke=1, fill=1)
    canv.setFillColorRGB(0, 0, 0)
    canv.setFont('Helvetica-Bold', 20)
    canv.drawString(margin + 10, title_rect_y + 15, title_text)

    #Body Section
    canv.setFont("Helvetica", 12)  # set font size back to 12
    canv.drawString(50, 680, f"This report provides a summary analysis of the Core Laboratory")
    canv.drawString(50, 650, f"The total amount of tasks created for the month was: {task_month_created}")
    canv.drawString(50, 630, f"The number of tasks completed for the month was: {task_month_completed}")
    canv.drawString(50, 610, f"The number of tasks in Planning state is: {task_month_planning}")
    canv.drawString(50, 590, f"The number of tasks in In-Progess state is: {task_month_progress}")
    canv.drawString(50, 575, f"The number of Sample Prep tasks created is: ")
    canv.drawString(50, 560, f"The number of Sample Prep tasks completed is: ")
    canv.save()
    return response

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}Lab Manager{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    {% block css_files %}

    {% endblock %}
</head>
<body>
{% include 'header.html' %}
<main>
{% block content %}

{% endblock %}
</main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/footer.html
<footer>
        <div>
        <h6> Core Manager developed by:</h6>
        <img src="static/images/cartoon_pug.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
        MiningGeek
        </div>

</footer>

templates/header.html
<style>
  .hello-msg {
    font-size = 18px;
    color: #fff;
    margin-right: 20px;
}
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home_app:index' %}">Core-Manager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'project_app:project_home_page' %}">Project <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'project_app:task_home_page' %}">Tasks</a>
      </li>
      {% if request.user.groups.all.0.name == 'Coordinator' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schedule_app:schedule_home' %}">Schedule</a>
        </li>
      {% endif %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'schedule_app:schedule_pm' %}">Schedule PM</a>
        </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'schedule_app:schedule_global' %}">Schedule Global</a>
        </li>
      {% if request.user.groups.all.0.name == 'Coordinator' %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Settings
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'home_app:monthly_report_form' %}"> Monthly Report</a>
            <a class="dropdown-item" href="{% url 'project_app:project_owners' %}"> Project Owner List</a>
            <a class="dropdown-item" href="{% url 'project_app:test_list' %}">Test List</a>
            <a class="dropdown-item" href="{% url 'project_app:technician_list' %}">Technician List</a>
            <a class="dropdown-item" href="{% url 'project_app:edit_reason_list' %}">Edit Reasons</a>
            <a class="dropdown-item" href="{% url 'project_app:task_edit_track' %}">Task Edit Tracking</a>
            <div class="dropdown-divider"></div>
            {% if request.user.is_superuser %}
              <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
          </div>
        </li>
      {% endif %}
    </ul>
    <span class="hello-msg">Hello, {{ request.user }} </span>
    <span ><a class="hello-msg" href="{% url 'home_app:logout' %}">Logout</a> </span>
  </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "home/home.css" %}">
  {% endblock %}

{% block page_title %}

{% endblock %}

{% block content %}
<center>
    <h1>Project Manager Home</h1>
</center>
<br>
<br>
<center><h2>Project Info</h2></center>
<section id="project">
    <div class="home">
        <center>
        <h3> # Planning </h3>
        <p> {{ planning_project_count }}</p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Ready </h3>
        <p>{{ ready_project_count }} </p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Active </h3>
        <p>{{ progress_project_count }} </p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # On-Hold </h3>
        <p>{{ hold_project_count }} </p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Completed </h3>
        <p> {{ completed_project_count }} </p>
        </center>
    </div>
</section>
<br>
<br>
<center><h2>Task Info</h2></center>
<section id="task">
    <div class="home">
        <center>
        <h3> # Planning</h3>
        <p> </p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Ready </h3>
        <p> </p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Active </h3>
        <p> </p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # Completed </h3>
        <p> </p>
        </center>
    </div>
    <div class="home">
        <center>
        <h3> # On-hold </h3>
        <p> </p>
        </center>
    </div>
</section>
<br>
<br>
<section id="quotes">

    <br>
        {{ quote }}

</section>
{% endblock %}