home/urls.py
from django.urls import path
from . import views

app_name = "home_app"
urlpatterns = [
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('45', views.home, name='home'),
    path('', views.index, name='index'),
    path('monthly_report_form', views.monthly_report_form, name='monthly_report_form'),
    path('generate_monthly_report', views.generate_monthly_report, name='generate_monthly_report')
    ]

labmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls')),
    path('', include('project.urls')),
    path('', include('schedule.urls')),
]

project/urls.py
from django.urls import path
from . import views
from django.apps import AppConfig

app_name = "project_app"

urlpatterns = [
    path('project_home_page', views.home, name='project_home_page'),
    path('project_owners', views.project_owners, name='project_owners'),
    path('test_list', views.test_list, name='test_list'),
    path('edit_test_list/<test_id>', views.edit_test_list, name='edit_test_list'),
    path('delet_test_list/<test_id>', views.delete_test_list, name='delete_test_list'),
    path('technician_list', views.technician_list, name='technician_list'),
    path('task_home_page', views.task_home_page, name="task_home_page"),
    path('add_task', views.add_task, name="add_task"),
    path('edit_project/<project_id>', views.edit_project, name="edit_project"),
    path('coord_edit_project/<project_id>', views.coord_edit_project, name="coord_edit_project"),
    path('delete_project/<project_id>', views.delete_project, name="delete_project"),
    path('pm_edit_task/<task_id>', views.pm_edit_task, name="pm_edit_task"),
    path('full_edit_task/<task_id>', views.full_edit_task, name="full_edit_task"),
    path('schedule_edit_task/<int:task_id>', views.schedule_edit_task, name="schedule_edit_task"),
    path('edit_project_owner/<project_owner_id>', views.edit_project_owner, name="edit_project_owner"),
    path('delete_project_owner/<project_owner_id>', views.delete_project_owner, name="delete_project_owner"),
    path('delete_technician/<technician_id>', views.delete_technician, name="delete_technician"),
    path('task_pdf/<task_id>', views.task_pdf, name='task_pdf'),
    path('edit_reason_list', views.viewTaskEdit, name='edit_reason_list'),
    path('delete_edit_reason/<edit_id>', views.delete_edit_reason, name='delete_edit_reason'),
    path('modify_edit_reason/<edit_id>', views.modify_edit_reason, name="modify_edit_reason"),
    path('task_edit_track', views.task_edit_track, name='task_edit_track'),
    path('test', views.test, name='test'),

    ]

home/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models

# Create your models here.

project_priority_list = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ]

status = [
    ('Planning', 'Planning'),
    ('Ready', 'Ready'),
    ('In-progress', 'In-progress'),
    ('On-hold', 'On-hold'),
    ('Completed', 'Completed'),
    ('Cancelled', 'Cancelled'),
]
suffix = [
    ('A', 'A'),
('B', 'B'),
('C', 'C'),
('D', 'D'),
('E', 'E'),
('F', 'F'),
('G', 'G'),
('H', 'H'),
('I', 'I'),
('J', 'J'),
('K', 'K'),
('L', 'L'),
('M', 'M'),
('N', 'N'),
]

shift = [
    ('FD', 'FD'),
    ('AM', 'AM'),
    ('PM', 'PM'),
    ('NS', 'NS'),
]

pulverise = [
    ('Yes', 'Yes'),
    ('No', 'No'),
    ('Other', 'Other'),
]
assay_loc = [
    ('Internal', 'Internal'),
    ('External', 'External'),
    ('Other', 'Other'),
]


class ProjectOwners(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    email_address = models.CharField(max_length=250, blank=True)
    status_active = models.BooleanField(default=True)
    project_owner_concat_name = models.CharField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        self.project_owner_concat_name = f"{self.first_name} {self.last_name}"
        super().save(*args, **kwargs)

    def __str__(self):
        return self.project_owner_concat_name


class Project(models.Model):
    project_number = models.CharField(max_length=50)
    project_suffix = models.CharField(max_length=10, choices=suffix, default="A")
    project_owner = models.ForeignKey(ProjectOwners, on_delete=models.CASCADE, blank=True)
    project_priority = models.CharField(max_length=20, choices=project_priority_list, default='3')
    project_status = models.CharField(max_length=25, choices=status, default='Planning')
    project_creation_date = models.DateField(auto_now_add=True)
    project_created_by = models.CharField(max_length=50)
    project_modified_by = models.CharField(max_length=50, null=True)
    project_modified_date = models.DateField(blank=True, null=True)
    project_concated_name = models.CharField(max_length=50, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.project_concated_name = f"{self.project_number} {self.project_suffix}"
        super().save(*args, **kwargs)

    def __str__(self):
        return self.project_concated_name


class Technician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    email_address = models.CharField(max_length=250, blank=True)
    technician_concat_name = models.CharField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        self.technician_concat_name = f"{self.first_name} {self.last_name}"
        super().save(*args, **kwargs)

    def __str__(self):
        return self.technician_concat_name


class TestList(models.Model):
    test = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.test


class Task(models.Model):
    task_name = models.CharField(max_length=200)
    task_suffix = models.CharField(max_length=10, choices=suffix, default="A")
    task_description = models.TextField()
    task_critical_path = models.IntegerField(default=1000)
    task_group = models.ForeignKey(TestList, on_delete=models.CASCADE, default="Nil")
    task_assigned_to = models.ForeignKey(Technician, on_delete=models.CASCADE, blank=True, null=True)
    task_request_date = models.DateField()
    task_created_by = models.CharField(max_length=30, blank=True)
    task_creation_date = models.DateTimeField(auto_now_add=True)
    task_status = models.CharField(max_length=25, choices=status, default='Planning')
    task_shift = models.CharField(max_length=25, choices=shift, default='FD')
    task_start_date = models.DateField(blank=True, null=True)
    task_end_date = models.DateField(blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task_pan = models.CharField(max_length=30)
    task_pulverise = models.CharField(max_length=10, choices=pulverise, default='No')
    task_assay_loc = models.CharField(max_length=15, choices=assay_loc, default='Internal')
    assay_method = models.TextField(blank=True, null=True)
    task_concated_name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.task_name


class EditReason(models.Model):
    edit_reason = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.edit_reason


class TaskEdit(models.Model):

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    edited_by = models.CharField(max_length=50)
    edit_date = models.DateTimeField(auto_now_add=True)
    edit_reason = models.ForeignKey(EditReason, on_delete=models.CASCADE, default="Nil", null=True)

    class Meta:
        ordering = ['-edit_date']

home/views.py
import random
import calendar
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate,login, logout
from django.http import HttpResponseRedirect, HttpResponse

from .utils import quotes
from django.contrib.auth.decorators import login_required
from project.models import Project, Task, ProjectOwners
from .decorators import unauthenticated_user, allowed_users, admin_only

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

from datetime import datetime
# Create your views here.

#just adding a note to hopefully push to server for a restart
@unauthenticated_user
def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home_app:index')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'home/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home_app:login')


@login_required(login_url='home_app:login')
def home(request):

    try:
        pm_first_name = request.user.first_name
        pm_last_name = request.user.last_name
        pm_name = pm_first_name + ' ' + pm_last_name
        pm_user = ProjectOwners.objects.get(project_owner_concat_name=pm_name)
        planning_project_count = Project.objects.filter(project_owner=pm_user, project_status='Planning' ).count()
        ready_project_count = Project.objects.filter(project_owner=pm_user, project_status='Ready').count()
        progress_project_count = Project.objects.filter(project_owner=pm_user, project_status='In-progress').count()
        hold_project_count = Project.objects.filter(project_owner=pm_user, project_status='On-hold').count()
        completed_project_count = Project.objects.filter(project_owner=pm_user, project_status='Completed').count()

        if request.user.username == "jenT":
            length = len(quotes)
            rand_quote = random.randint(0, length)
            quote = quotes[rand_quote - 1]
            context = {
                'planning_project_count': planning_project_count,
                'ready_project_count': ready_project_count,
                'progress_project_count': progress_project_count,
                'hold_project_count': hold_project_count,
                'completed_project_count': completed_project_count,
                'quote': quote,
            }
        else:
            context = {
                'planning_project_count': planning_project_count,
                'ready_project_count': ready_project_count,
                'progress_project_count': progress_project_count,
                'hold_project_count': hold_project_count,
                'completed_project_count': completed_project_count,

            }
        return render(request, 'home.html', context)
    except ProjectOwners.DoesNotExist as e:
        pm_first_name = request.user.first_name
        pm_last_name = request.user.last_name
        pm_name = pm_first_name + ' ' + pm_last_name
        print(pm_name)

        return render(request, 'home.html')



@login_required(login_url='home_app:login')
@admin_only
def index(request):
    length = len(quotes)
    rand_quote = random.randint(0,length)
    quote = quotes[rand_quote-1]
    planning_project_count = Project.objects.filter(project_status='Planning').count()
    ready_project_count = Project.objects.filter(project_status='Ready').count()
    active_project_count = Project.objects.filter(project_status='In-progress').count()
    hold_project_count = Project.objects.filter(project_status='On-hold').count()
    completed_project_count = Project.objects.filter(project_status='Completed').count()

    planning_task_count = Task.objects.filter(task_status='Planning').count()
    ready_task_count = Task.objects.filter(task_status='Ready').count()
    active_task_count = Task.objects.filter(task_status='In-progress').count()
    hold_task_count = Task.objects.filter(task_status='On-hold').count()
    completed_task_count = Task.objects.filter(task_status='Completed').count()
    context = {
        'quote': quote,
        'planning_project_count':planning_project_count,
        'ready_project_count': ready_project_count,
        'active_project_count': active_project_count,
        'hold_project_count': hold_project_count,
        'completed_project_count': completed_project_count,
        'planning_task_count': planning_task_count,
        'ready_task_count': ready_task_count,
        'active_task_count': active_task_count,
        'hold_task_count': hold_task_count,
        'completed_task_count': completed_task_count,


    }
    return render(request, 'home/home.html', context)


@login_required(login_url='home_app:login')
def monthly_report_form(request):
    return render(request, 'home/monthly_report_form.html')


@login_required(login_url='home_app:login')
def generate_monthly_report(request):
    month = request.GET.get('month')
    year = request.GET.get('year')
    month_name = calendar.month_name[int(month)]

    #find first day of month
    start_date= datetime.strptime(f"{year}-{month}-01","%Y-%m-%d").date()

    #find last day of month
    if month == '12':
        end_date = datetime.strptime(f"{int(year)+1}-01-01", "%Y-%m-%d").date()
    else:
        end_date = datetime.strptime(f"{year}-{int(month)+1}-01", "%Y-%m-%d").date()

    filename = f'monthly_report_{month}_{year}.pdf'
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'

    canv = canvas.Canvas(response, pagesize=A4)

    #draw logo to report
    img_path = "static/images/core-logo.png"
    img = ImageReader(img_path)
    img_width, img_height = img.getSize()
    canv.drawImage(img, 0, A4[1] - img_height, width=img_width, height=img_height)

    #get the number of tasks created etc in a selected month and year
    task_month_created = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date).count()
    task_month_completed = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date, task_status='Completed').count()
    task_month_planning = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date,
                                               task_status='Planning').count()
    task_month_progress = Task.objects.filter(task_creation_date__gte=start_date, task_creation_date__lt=end_date,
                                              task_status='In-progress').count()

    #Title Section
    canv.setFillColorRGB(255, 255, 255)
    canv.setStrokeColorRGB(0.5, 0.5, 0.5)
    margin = 20
    title_rect_height = 40
    title_rect_y = 715
    title_rect_width = A4[0] - 2 * margin
    title_text = f"Laboratory Monthly Report for {month_name} {year}"
    canv.rect(margin, title_rect_y, title_rect_width, title_rect_height, stroke=1, fill=1)
    canv.setFillColorRGB(0, 0, 0)
    canv.setFont('Helvetica-Bold', 20)
    canv.drawString(margin + 10, title_rect_y + 15, title_text)

    #Body Section
    canv.setFont("Helvetica", 12)  # set font size back to 12
    canv.drawString(50, 680, f"This report provides a summary analysis of the Core Laboratory")
    canv.drawString(50, 650, f"The total amount of tasks created for the month was: {task_month_created}")
    canv.drawString(50, 630, f"The number of tasks completed for the month was: {task_month_completed}")
    canv.drawString(50, 610, f"The number of tasks in Planning state is: {task_month_planning}")
    canv.drawString(50, 590, f"The number of tasks in In-Progess state is: {task_month_progress}")
    canv.drawString(50, 575, f"The number of Sample Prep tasks created is: ")
    canv.drawString(50, 560, f"The number of Sample Prep tasks completed is: ")
    canv.save()
    return response

templates/project/edit_project.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Edit Project</h2>

 <form action="" method=POST>
        {% csrf_token %}
        {{ form.as_p }}
        <br/>
        <input type="submit" value="Update" class="btn btn-secondary">
    </form>





{% endblock %}

templates/project/edit_project_owner.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Edit Project Owners List</h2>

{% if submitted %}
    Your task was submitted was sucessfully
{% else %}


    <form class="add_task" action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Submit" class="btn btn-success">

    </form>

{% endif %}




{% endblock %}

templates/project/edit_task.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Title</h2>




{% endblock %}

templates/project/edit_test_list.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Title</h2>

{% if submitted %}
    Your task was submitted was sucessfully
{% else %}


    <form class="add_task" action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Submit" class="btn btn-success">

    </form>

{% endif %}



{% endblock %}

templates/project/full_edit_task.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Full Edit Task</h2>

{% if submitted %}
    Your task was submitted was sucessfully
{% else %}


    <form class="add_task" action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Submit" class="btn btn-success">

    </form>

{% endif %}




{% endblock %}

templates/project/generic.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Title</h2>




{% endblock %}

templates/project/home.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Add Project</h2>


{% if submitted %}
    Your project was submitted was successfully
{% else %}

    <form class="form_add" action="" method="POST">
        {% csrf_token %}

        {{ form }}
        <input type="submit" value="Submit" name="submit_form" class="btn btn-success">

    </form>
{% endif %}
<br/>
<div class="table_sort">
    <form method="POST" action="">
        {% csrf_token %}
        <input type="radio" value="Default" name="project_status"/> Default
        <input type="radio" value="Planning" name="project_status"/> Planning
        <input type="radio" value="Ready" name="project_status"/> Ready
        <input type="radio" value="In-progress" name="project_status"/> In-progress
        <input type="radio" value="On-hold" name="project_status"/> On-hold
        <input type="radio" value="Completed" name="project_status"/> Completed
        <input type="radio" value="Cancelled" name="project_status"/> Cancelled
        <input type="radio" value="All" name="project_status"/> Show All
        <input class="btn btn-secondary" type="submit" value="Filter" name="project_filter">
    </form>
</div>

<table id="project_table" class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Project Number</th>
        <th scope="col">Project Owner</th>
        <th scope="col">Project Priority</th>
        <th scope="col">Date Created</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
        <th scope="col"></th>

    </tr>
    </thead>
    <tbody>
   {% if project_list %}
    {% for project in project_list %}
        <tr>
            <th scope="row">{{project.project_concated_name}}</th>
            <td>{{project.project_owner}}</td>
            <td>{{project.project_priority}}</td>
            <td>{{project.project_creation_date}}</td>
            <td>{{project.project_status}}</td>
            {% if request.user.groups.all.0.name == 'projectmanager' %}
            <td><a href="{% url 'project_app:edit_project' project.id %}" class="btn btn-secondary">Edit</a></td>
            {% endif %}
            {% if request.user.groups.all.0.name == 'Coordinator' %}
                <td><a href="{% url 'project_app:coord_edit_project' project.id %}" class="btn btn-secondary">Edit</a></td>
                <td><a href="{% url 'project_app:delete_project' project.id %}" class="btn btn-danger">Delete</a></td>
            {% endif %}

        </tr>
    {% endfor %}

{% endif %}


    </tbody>

</table>

{% endblock %}

templates/project/modify_edit_reason.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Modify Edit Reason</h2>

<form class="form_add" action="" method="POST">
        {% csrf_token %}

        {{ form }}

        <input id="form_submit" type="submit" value="Submit" class="btn btn-secondary">

</form>


{% endblock %}

templates/project/pm_edit_task.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>PM Edit Task</h2>

<form class="task_form" action="" method=POST>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Update" class="btn btn-secondary">
</form>



{% endblock %}

templates/project/project_owner.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}
<h2>Project Owners</h2>

{% if submitted %}

{% else %}

    <form class="form_add" action="" method="POST">
        {% csrf_token %}

        {{ form }}

        <input id="form_submit" type="submit" value="Submit" name="submit_form" class="btn btn-success">

    </form>
{% endif %}

<br/>
<div class="table_sort">
    <form method="POST" action="">
        {% csrf_token %}
        <input class="radio_filter" type="radio" value="True" name="project_owner_status"/> Show Active
        <input class="radio_filter" type="radio" value="False" name="project_owner_status"/> Show In-Active
        <input class="radio_filter" type="radio" value="Default" name="project_owner_status"/> Show All

        <input class="btn btn-secondary" type="submit" value="Filter" name="project_filter">
    </form>
</div>
<br/>
<table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email Address</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
        <th scope="col"></th>


    </tr>
    </thead>
    <tbody>
{% if project_owner_list %}
    {% for owner in project_owner_list %}
        <tr>
            <th scope="row">{{owner.first_name}}</th>
            <td>{{owner.last_name}}</td>
            <td>{{owner.email_address}}</td>
            <td>{{owner.status_active}}</td>
            <td><a href="{% url 'project_app:edit_project_owner' owner.id %}" class="btn btn-secondary">Edit</a></td>
            <td><a href="{% url 'project_app:delete_project_owner' owner.id %}" class="btn btn-secondary">Delete</a></td>


        </tr>
    {% endfor %}

{% endif %}

    </tbody>

</table>


{% endblock %}

templates/project/task_edit_track.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Task Edit Tracking</h2>

<table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Task</th>
        <th scope="col">Edited By</th>
        <th scope="col">Edit Date</th>
        <th scope="col">Edit Reason</th>


    </tr>
    </thead>
    <tbody>
{% if track_edit_list %}
    {% for edit in track_edit_list %}
        <tr>
            <th scope="row">{{edit.task}}</th>
            <td>{{edit.edited_by}}</td>
            <td>{{edit.edit_date}}</td>
            <td>{{edit.edit_reason}}</td>

        </tr>
    {% endfor %}

{% endif %}

    </tbody>

</table>



{% endblock %}

templates/project/task_home_page.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}

<h2>Tasks</h2>
<a class="btn btn-primary btn-lg" href="{% url 'project_app:add_task' %}" role="button">Add Task</a>
<table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Project</th>
        <th scope="col">Project Priority</th>
        <th scope="col">Task Name</th>
        <th scope="col">Suffix</th>
        <th scope="col">Task Status</th>
        <th scope="col">Description</th>
        <th scope="col">Critical Path #</th>
        <th scope="col">Test Group</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Technician</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>

    </tr>
    </thead>
    <tbody>
         {% if task_list %}
    {% for task in task_list %}
        <tr>
            <th scope="row">{{task.project}}</th>
            <td>{{task.project.project_priority}}</td>
            <td>{{task.task_name}}</td>
            <td>{{task.task_suffix}}</td>
            <td>{{task.task_status}}</td>
            <td>{{task.task_description}}</td>
            <td>{{task.task_critical_path}}</td>
            <td>{{task.task_group}}</td>
            <td>{{task.task_start_date}}</td>
            <td>{{task.task_end_date}}</td>
            <td>{{task.task_assigned_to}}</td>
            {% if request.user.groups.all.0.name == 'projectmanager' %}
                <td><a href="{% url 'project_app:pm_edit_task' task.id %}" class="btn btn-secondary">Edit</a></td>
            {% endif %}
            {% if request.user.groups.all.0.name == 'Coordinator' %}
                <td><a href="{% url 'project_app:full_edit_task' task.id %}" class="btn btn-secondary"> Edit </a></td>
                <td><a href="{% url 'project_app:task_pdf' task.id %}" class="btn btn-secondary">Create PDF</a></td>
            {% endif %}


        </tr>
    {% endfor %}

{% endif %}

    </tbody>

</table>


{% endblock %}

templates/project/technician_list.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}
{% block page_title %}

{% endblock %}

{% block content %}
<br/>
<h2>Add Tech</h2>

<br/>


    <form class="form_add" action="" method="POST">
        {% csrf_token %}

        {{ form }}

        <input id="form_submit" type="submit" value="Submit" class="btn btn-secondary">

    </form>


<br/>
<br/>
<table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col"></th>
        <th scope="col"></th>



    </tr>
    </thead>
    <tbody>
{% if tech_list %}
    {% for tech in tech_list %}
        <tr>
            <th scope="row">{{tech.first_name}}</th>
            <td>{{tech.last_name}}</td>

            <td><a href="#" class="btn btn-secondary">Edit - not set up</a></td>
            <td><a href="{% url 'project_app:delete_technician' tech.id %}" class="btn btn-danger">Remove</a></td>

        </tr>
    {% endfor %}

{% endif %}


    </tbody>

</table>

{% endblock %}

templates/project/test_list.html
{% extends 'base.html' %}
{% load static %}

 {% block css_files %}
        <link rel="stylesheet" href="{% static "project/project.css" %}">
  {% endblock %}

{% block page_title %}

{% endblock %}

{% block content %}
<h2>Test List</h2>

<div class="form_add">
      <form action="" method="POST">
        {% csrf_token %}

        {{ form }}

        <input id="form_submit" type="submit" value="Submit" class="btn btn-success">

    </form>
</div>
<br/>
<br/>

<table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Test Name</th>

        <th scope="col"></th>
        <th scope="col"></th>

    </tr>
    </thead>
    <tbody>
          {% if tests %}
            {% for test in tests %}
                <tr>
                    <th scope="row">{{test.test}}</th>

                    <td><a href="{% url 'project_app:edit_test_list' test.id %}" class="btn btn-secondary">Edit</a></td>
                    <td><a href="{% url 'project_app:delete_test_list' test.id %}" class="btn btn-secondary">Remove</a></td>

                </tr>
            {% endfor %}

          {% endif %}


    </tbody>

</table>
{% endblock %}